
ORDERS_START, STOP = map(chr, range(2))
SELECTING_PLACE, KITCHEN, BAR, ZEH, ADD_NEW_POSITION, ADD = map(chr, range(2, 8))
CREATING_ORDER, SENDING_ORDER, HISTORY, CHANGE_ORDER, CLOSING_ORDER, DELETING_ORDER, DELETE_FROM_ORDER, TYPING, TYPING_COUNT = map(chr, range(8, 17))
MENU, START = map(chr, range(17, 19))
REPORTING, GET_REPORT, GET_REPORT_XLSX, KITCHEN_REPORT, BAR_REPORT, ZEH_REPORT = map(chr, range(19, 25))

END = map(chr, range(98, 99))

DELETE_MESSAGE_PAUSE = 5