
ORDERS_START, STOP = map(chr, range(2))
SELECTING_PLACE, KITCHEN, BAR, ZEH, ADD_NEW_POSITION, ADD = map(chr, range(2, 8))
CREATING_ORDER, SENDING_ORDER, HISTORY, ADD_TO_ORDER, CLOSING_ORDER, DELETING_ORDER, DELETE_FROM_ORDER, TYPING = map(chr, range(8, 15))
MENU, START = map(chr, range(15, 17))
REPORTING, GET_REPORT, GET_REPORT_XLSX, KITCHEN_REPORT, BAR_REPORT, ZEH_REPORT = map(chr, range(17, 23))

END = map(chr, range(98, 99))

DELETE_MESSAGE_PAUSE = 5